version: '3.8'
services:
    app:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: delivery_api
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
